spring.data.mongodb.uri: mongodb://localhost/flap_db
---

spring:
    profiles: development
spring.data.mongodb.uri: mongodb://localhost/flap_db

---

spring:
    profiles: staging
spring.data.mongodb.uri: mongodb://matchPrizeWebApp:webappdbpass@ds061691.mongolab.com:61691/matchprize-staging

---

spring:
    profiles: production
spring.data.mongodb.uri: mongodb://matchPrizeWebApp:webappdbpass@ds043971.mongolab.com:43971/matchprize-prod
